# Generated by Django 3.2.9 on 2021-11-15 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registrationsystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('report', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GradeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('report', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses', models.ManyToManyField(to='registrationsystem.Course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses', models.ManyToManyField(to='registrationsystem.Course')),
                ('enrollmentSummaries', models.ManyToManyField(to='registrationsystem.EnrollmentSummary')),
                ('gradeReports', models.ManyToManyField(to='registrationsystem.GradeReport')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='gradereport',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='registrationsystem.course'),
        ),
        migrations.CreateModel(
            name='DropRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='registrationsystem.course')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='registrationsystem.student')),
            ],
        ),
        migrations.CreateModel(
            name='AddRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='registrationsystem.course')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='registrationsystem.student')),
            ],
        ),
    ]
