# Generated by Django 3.2.9 on 2021-11-15 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrationsystem', '0002_auto_20211115_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradereport',
            name='course',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='courses',
        ),
        migrations.AddField(
            model_name='course',
            name='enrollmentSummary',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='registrationsystem.enrollmentsummary'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='gradeReport',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='registrationsystem.gradereport'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='professor',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='registrationsystem.professor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='professor',
            name='enrollmentSummaries',
            field=models.ManyToManyField(blank=True, to='registrationsystem.EnrollmentSummary'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='gradeReports',
            field=models.ManyToManyField(blank=True, to='registrationsystem.GradeReport'),
        ),
        migrations.AlterField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(blank=True, to='registrationsystem.Course'),
        ),
    ]
