# Generated by Django 3.2.9 on 2021-11-15 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationsystem', '0003_auto_20211115_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
