# Generated by Django 3.2.9 on 2021-11-15 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrationsystem', '0007_auto_20211115_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='registrationsystem.professor'),
        ),
    ]
